site_name: Django sidecar
site_url: https://example.com/
theme: 
  name: material
  highlightjs: true
  hljs_languages:
    - bash
nav:
- Home: index.md
- Tutorial: tutorial.md
- Features: features.md
